version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
  backend:
    # image: a20688392/ipfs-blog-backend:0.0.1
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    command: /bin/sh -c "sh /migration-entrypoint.sh"
    env_file:
    - .env
    ports:
      - 3000:3000
    depends_on:
      - db